### ISSUE TITLE
reset previous tab data

### ISSUE THREAD

**Issue by sh4msi** [zenonine/navi#34]
hi,
whenever I switch between tabs, I need the previous tab to reset(initialize)
(in nested navigation)

**Comment by xuanswe** [comment]
Hi @sh4msi Could you please explain your question more details? I do not understand your question.

Did you check the new example I made yesterday: https://github.com/zenonine/navi/tree/master/examples/nested-routing-bottom-navigation-bar? The similar old example was only the first try and it seems the new one is much more easier and stable.

I am finding the new easier way to use RouteStack with BottomNavigationBar. There's just one thing I will update soon is how to keep the state of tabs in this new example.

**Comment by sh4msi** [comment]
Thanks.
I want the stack to return to normal when I exit the current nested tab (BottomNavigationBar).
(When I enter a new (different) tab, the previous nested tab returns to its home page)

> I will definitely test the new example 
> Did you create a comfortable mode for the nested BottomNavigationBar?

**Comment by xuanswe** [comment]
Then I think it's exactly what the new example is doing right now. Each time you open a tab, it is reset to normal.

I will update to optionally remember state in the example and explain the mechanism to decide which tab should remember state, which tab should not after that.

Is my answer satisfy your question?

**Comment by xuanswe** [comment]
I can confirm that, if you are not targeting the web, then the library is working quite ok for not.

For targeting web, the URL synchronization is not stable yet for complicated scenarios, such as, keeping state of tabs (but you want to reset so don't need to worry about it). I am trying different architecture approaches to find the most stable way for this problem.

**Comment by sh4msi** [comment]
I will test your example
I just do not know how to add different pages to tabs

> navi document is not complete

**Comment by xuanswe** [comment]
Sorry, don't have time for a complete documentation for this case.

> I just do not know how to add different pages to tabs

Each tab is just a page of a RouteStack.
When you switch tab, update to have another page in your RouteStack.
Inside each tabs, you can have inner RouteStack, which can contains multiple child pages.
Just run the example locally then see the code, it's not so difficult to understand I think.

**Comment by xuanswe** [comment]
Please check new version 0.2.0-rc+0, new [documentation](https://github.com/zenonine/navi/tree/master/navi) and new [examples](https://github.com/zenonine/navi/tree/master/examples).
