### ISSUE TITLE
Multiple path history

### ISSUE THREAD

**Issue by plavunov** [zenonine/navi#61]
Hi, and thanks for the fantastic package!

I'm trying to implement an Instagram-like flow with IndexedStack, where each bottom bar item is a separate NaviStack.

The issue is that the history for some of the NaviStacks can look like:

/profile_3523/profile_111/profile_4634/ (etc. etc.)

where _(number) is the ID of the profile.

So I succeeded in building this incremental path for a NaviStack (and getting user Id out of it), but I'm having trouble popping this (and therefore reducing the path by one item at a time).

Seem like context.navi.back() could be the ideal solution, but maybe there is something I'm missing?

**Comment by xuanswe** [comment]
Hi @plavunov, sorry for late reply. I've just come back from a long vacation. I will try to answer your question shortly.

**Comment by xuanswe** [comment]
* Firstly, `context.navi.back()` is in TODO list, not yet implemented (see current documentation)
* Secondly, please keep in mind that we have [2 kinds of navigation](https://material.io/design/navigation/understanding-navigation.html#reverse-navigation): **chronologically** through their recent screen history, or **upwards** through an app's hierarchy.

As far as I am understanding your case correctly, you want to use **chronologically** navigation by keeping the history in your URL structure. I honestly suggest you should not try to do that, regardless using Navi or not.

You should only use URL structure to map to app's hierarchy.

`Navi` currently implements only navigation through an app's hierarchy. In `Navi`, you manage app's hierarchy using nested stacks and the page list in each stack.
So right now, you cannot yet use this library to navigate chronologically.

I think, until chronologically navigation is supported, the best solution is to keep a list of profile ids in your app state.

For example,
Your history of profile ids are 111, 222, 333.
Your current profile id is 444. => your current URL is profiles/444.
Navigate to previous profile => URL should be profiles/333.
